name: PR Checks
on:
  push: { branches: [main] }
  pull_request: {}
jobs:
  checks:
    uses: adesso-mobile-open-source/workflows-swift/.github/workflows/pr-checks.yml@v1.0.1
    secrets: inherit
    with:
      linux: always
